unit uNetWorkTest;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.Classes, uNetWork, System.SysUtils;

type
  // Test methods for class NetWork

  TestNetWork = class(TTestCase)
  strict private
    FNetWork: NetWork;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestConnect;
    procedure TestQuery;
  end;

implementation

procedure TestNetWork.SetUp;
begin
  FNetWork := NetWork.Create(8);
end;

procedure TestNetWork.TearDown;
begin
  FNetWork.Free;
  FNetWork := nil;
end;

procedure TestNetWork.TestConnect;
var
  element2: Integer;
  element1: Integer;
begin
  element1 := 1;
  element2 := 2;

  FNetWork.Connect(element1, element2);
  CheckTrue(FNetWork.Query(element1, element2), 'A função de Connect falhou!');
end;

procedure TestNetWork.TestQuery;
var
  ReturnValue: Boolean;
  element2: Integer;
  element1: Integer;
begin
  element1 := 2;
  element2 := 6;

  FNetWork.Connect(element1, element2);

  ReturnValue := FNetWork.Query(2, 6);

  CheckTrue(ReturnValue, 'A função de Query falhou!');
end;

initialization
  RegisterTest(TestNetWork.Suite);
end.

